/**
 * Video scene data — generated by /videoflow:compose from .videoflow/SCENES.md
 *
 * This file is the bridge between the VideoFlow planning system and Remotion.
 * The videoflow-composer agent reads SCENES.md + assets/ and generates this file.
 */

export const DEFAULTS = {
  fadeFrames: 15,
  fadeToBlackFrames: 20,
  fontSize: 52,
  kenBurnsScale: 1.05,
  textPadding: 60,
  textPositionTop: 80,
  textPositionBottom: 100,
  textShadow: "2px 2px 12px rgba(0,0,0,0.9)",
} as const;

export interface SceneData {
  id: number;
  type: "image" | "clip";
  src: string; // Path relative to public/ (used with staticFile)
  durationSeconds: number;
  text?: string;
  textPosition?: "top" | "center" | "bottom";
  voiceover?: string; // Path to audio file
  transition?: "cut" | "crossfade" | "fade-to-black";
  fontSize?: number; // Override default font size
  kenBurns?: boolean; // Enable/disable Ken Burns effect (default: true)
  volume?: number; // Voiceover volume (default: 1.0)
}

export interface VideoData {
  fps: number;
  width: number;
  height: number;
  scenes: SceneData[];
  backgroundMusic?: {
    src: string;
    volume: number;
  };
}

// Placeholder data — replaced by /videoflow:compose
export const videoData: VideoData = {
  fps: 30,
  width: 1920,
  height: 1080,
  scenes: [
    {
      id: 1,
      type: "image",
      src: "assets/images/scene-01.png",
      durationSeconds: 5,
      text: "Your video starts here",
      textPosition: "center",
      transition: "crossfade",
    },
  ],
  backgroundMusic: undefined,
};
